spring:
  application:
    name: manager
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    constructor-detector: use_properties_based

server:
  port: 8901

app:
  workers:
    count: 2
    baseUrl: ""
